# Generated by Django 2.2.4 on 2020-02-20 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_delivery', models.CharField(blank=True, choices=[(1, 'delivery_type_1'), (2, 'delivery_type_2')], max_length=55, null=True)),
                ('sex', models.CharField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], max_length=10, null=True)),
                ('live_birth', models.BooleanField(default=True)),
                ('still_birth', models.BooleanField(default=False)),
                ('preterm', models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(8))),
                ('abortion_types', models.CharField(blank=True, choices=[(1, 'Medical'), (2, 'Vaccum Aspiration - Surgical'), (3, 'Dilation & Curettage(D&C) - Surgical'), (4, 'Gravid Hysterectomy - Surgical'), (5, 'Labour Induction Abortion')], max_length=50, null=True)),
                ('heart_rate_1_min_value', models.CharField(blank=True, max_length=10, null=True)),
                ('heart_rate_1_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('muscle_tone_1_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('muscle_tone_1_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('reflex_1_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('reflex_1_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('colour_1_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('colour_1_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('respiratory_effort_1_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('respiratory_effort_1_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('heart_rate_5_min_value', models.CharField(blank=True, max_length=10, null=True)),
                ('heart_rate_5_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('muscle_tone_5_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('muscle_tone_5_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('reflex_5_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('reflex_5_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('colour_5_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('colour_5_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('respiratory_effort_5_min_value', models.CharField(blank=True, max_length=100, null=True)),
                ('respiratory_effort_5_min_slot', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedicalTerminationOfPregnancyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField(default='2019-12-13')),
                ('name_of_patient', models.CharField(default='name', max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)])),
                ('weight', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(999)])),
                ('duration_of_pregnancy', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(52)])),
                ('reason_of_termination', models.TextField(blank=True, null=True)),
                ('type_of_abortion', models.CharField(blank=True, choices=[(1, 'Medical'), (2, 'Vaccum Aspiration - Surgical'), (3, 'Dilation & Curettage(D&C) - Surgical'), (4, 'Gravid Hysterectomy - Surgical'), (5, 'Labour Induction Abortion')], max_length=100, null=True)),
                ('date_of_termination', models.DateField(blank=True, null=True)),
                ('date_of_discharge', models.DateField(blank=True, null=True)),
                ('results_and_remarks', models.TextField(blank=True, null=True)),
                ('post_abortion_complication_identified', models.TextField(blank=True, null=True)),
                ('post_abortion_complication_treated', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
