# Generated by Django 2.2.4 on 2020-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternity_extended', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrecord',
            name='type_of_delivery',
            field=models.CharField(blank=True, choices=[(1, 'delivery_type_1'), (2, 'delivery_type_2')], max_length=66, null=True),
        ),
    ]
