# Generated by Django 2.2.4 on 2020-02-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0001_initial'),
        ('maternity_extended', '0002_auto_20200220_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrecord',
            name='maternity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maternity.MaternityDetails'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
