# Generated by Django 2.2.4 on 2020-02-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternity_extended', '0003_auto_20200224_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalterminationofpregnancyrecord',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='deliveryrecord',
            table='maternity_extended_deliveryrecord',
        ),
    ]
