# Generated by Django 2.2.4 on 2020-02-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maternity_extended', '0004_auto_20200224_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryrecord',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='medicalterminationofpregnancyrecord',
            table='maternity_extended_medicalterminationofpregnancyrecord',
        ),
    ]
