# Generated by Django 2.2.4 on 2020-03-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObstetricForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.CharField(blank=True, max_length=100, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=100, null=True)),
                ('sexually_transmitted_disease', models.CharField(blank=True, max_length=100, null=True)),
                ('pyelonephritis_uti', models.CharField(blank=True, max_length=100, null=True)),
                ('acute_surgical_problem', models.CharField(blank=True, max_length=100, null=True)),
                ('genital_tract_abnormalities', models.CharField(blank=True, max_length=100, null=True)),
                ('maternal_age', models.IntegerField()),
                ('maternal_weight', models.FloatField()),
                ('maternal_height', models.FloatField()),
                ('exposure_of_teratogens', models.CharField(blank=True, max_length=100, null=True)),
                ('exposure_to_mercury', models.CharField(blank=True, max_length=100, null=True)),
                ('prior_stillbirth', models.IntegerField(blank=True, null=True)),
                ('prior_preterm_delivery', models.IntegerField(blank=True, null=True)),
                ('prior_neonate_with_genitic_or_congenital_disorder', models.TextField(blank=True, null=True)),
                ('polyhydramnios_and_oligohydramnios', models.CharField(blank=True, max_length=100, null=True)),
                ('multifetal_pregnancy', models.IntegerField(blank=True, null=True)),
                ('prior_birth_injury', models.TextField(blank=True, null=True)),
                ('gravidity_and_parity', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObstetricPhysicalExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesions_or_discharge', models.CharField(max_length=100)),
                ('colour_and_consistency_of_cervix', models.CharField(max_length=100)),
                ('cervical_samples_for_testing', models.CharField(blank=True, max_length=100, null=True)),
                ('pelvic_capacity', models.CharField(max_length=100)),
                ('blood_pressure', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('uterine_size', models.CharField(max_length=100)),
                ('fundal_weight', models.FloatField()),
                ('fetal_heart_rate_and_activity', models.CharField(max_length=100)),
                ('maternal_diet', models.TextField()),
                ('weight_gain', models.FloatField()),
                ('date_of_examination', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('visit_no', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('obstetric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstetric.ObstetricForm')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
