# Generated by Django 2.2.4 on 2020-03-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obstetric', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obstetricform',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='obstetricphysicalexamination',
            options={'managed': False},
        ),
    ]
