# Generated by Django 3.0.3 on 2020-03-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.IntegerField(blank=True, null=True)),
                ('booking_id', models.CharField(blank=True, max_length=110, null=True)),
                ('patient_id', models.IntegerField()),
                ('preg_no', models.IntegerField()),
                ('patient_name', models.CharField(max_length=255)),
                ('doctor_name', models.CharField(max_length=255)),
                ('active_medical_issues', models.TextField()),
                ('active_pregnancy_issues', models.TextField()),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_contact', models.CharField(max_length=255)),
                ('partner_user_id', models.IntegerField()),
                ('delivery_hospital_id', models.IntegerField()),
                ('delivery_hospital_name', models.CharField(max_length=255)),
                ('hospital_reg_number', models.CharField(max_length=251)),
                ('lnmp_date', models.DateField()),
                ('conception_date', models.DateField()),
                ('expected_date_of_delivery', models.DateField()),
                ('current_gestation', models.IntegerField()),
                ('folloupdate', models.DateField()),
                ('created_date', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('updated_date', models.DateTimeField()),
                ('updated_by', models.IntegerField()),
            ],
            options={
                'db_table': 'maternity_details',
                'managed': False,
            },
        ),
    ]
